### ISSUE TITLE
Android

### ISSUE THREAD

**Issue by popking159** [gorgone/s3_releases#1]
Please add Android toolchain cfg , for Android nougat API 24 , THANKS

**Comment by gorgone** [comment]
can u provide a toolchain ?

**Comment by mesofranico** [comment]
https://github.com/nx111/oscam/blob/master/toolchains/toolchain-arm-android.cmake

https://github.com/nx111/oscam/blob/master/build/build_arm/build_android.sh

**Comment by gorgone** [comment]
these are no toolchains but build scripts

**Comment by atarist** [comment]
can you make sb for minisatip or/& satpi?
very useful apps but hard to cross compile for noobs ;)

**Comment by gorgone** [comment]
u can only build if there is support on the oscam source itself !
