### ISSUE TITLE
 CARDREADER_STAPI5

### ISSUE THREAD

**Issue by GHOSt19dZ** [gorgone/s3_releases#2]
please fix this problem  CARDREADER_STAPI5
not active for simplebuild 
look for my profile i'm active my CARDREADER_STAPI5 and after build I find it not working

[stapi5.zip](https://github.com/gorgone/s3_releases/files/2923639/stapi5.zip)

**Comment by gorgone** [comment]
which toolchain u use ?

**Comment by gorgone** [comment]
tested with sh4 no problem to build
describe exactly the issue with **### simplebuild**

**Comment by GHOSt19dZ** [comment]
> which toolchain u use ?

i'use toolchain sh_4

**Comment by GHOSt19dZ** [comment]
> tested with sh4 no problem to build
> describe exactly the issue with **### simplebuild**

The problem is when the profile is used directly
 like this : ./s3 sh_4 -p=stapi5.profile

**Comment by gorgone** [comment]
post the profile please

**Comment by gorgone** [comment]
tested 
./s3 sh_4 USE_STAPI5
works ok ...
u say in profile its not working ?

**Comment by gorgone** [comment]
tested with profile also ok
with profile:
 LINK ------->  /opt/s3_releases/support/binaries/oscam-svn11513-sh_4-webif-dvbapi-stapi5.debug
 STRIP ------>  /opt/s3_releases/support/binaries/oscam-svn11513-sh_4-webif-dvbapi-stapi5
and manual
 LINK ------->  /opt/s3_releases/support/binaries/oscam-svn11513-sh_4-webif-dvbapi-stapi5.debug
 STRIP ------>  /opt/s3_releases/support/binaries/oscam-svn11513-sh_4-webif-dvbapi-stapi5

**Comment by gorgone** [comment]
` |       set : USE_UTF8=1
 |       set : USE_LIBCRYPTO=1
 |       set : USE_STAPI5=1
 |       LIB : liboscam_stapi5_OPENBOX.a
 |   PROFILE : stapi.profile
`

**Comment by andalasopen** [comment]
how do i add constantcw

**Comment by Mickey7779** [comment]
Good afternoon, please fix the error in liboscam_stapi5_OPENBOX. a, since the card reader does not work with this version, instead
of liboscam_stapi5_OPENBOX. a set liboscam_stapi5_UFS916_0. 03. a and the card reader is working
