### ISSUE TITLE
USE_PATCH not working from the menu

### ISSUE THREAD

**Issue by messi89** [gorgone/s3_releases#47]
Hello;

As mentioned on the title using the option "USE_PATCH" from the menu is not working any more (looks like the script do an svn restore before build)

`./s3 menu with USE_PATCH` not work

I need to use svn patch manually on the oscam-svn folder before building
`svn patch ../patches/my_awesome.patch`
`./s3 native without_use_patch` 

Regards;

**Comment by gorgone** [comment]
./s3 update_me
./s3 enable_emu
./s3 menu native

**Comment by messi89** [comment]
still ignore patchs in patches folder
