### ISSUE TITLE
error during compiling sh_4

### ISSUE THREAD

**Issue by popking159** [gorgone/s3_releases#48]
error in module-emulator-biss
`    ___  ____   ___
   / _ \/ ___| / __|__ _ _ __ ___
  | | | \___ \| |  / _` | '_ ` _ \ 
  | |_| |___) | |_| (_| | | | | | |
   \___/|____/ \___\__,_|_| |_| |_|
   
+-------------------------------------------------------------------------------
| OSCam ver: 1.20_svn rev: 11638-798 target: sh4-streamboard-linux-gnu
| Tools:
|  CROSS    = /root/s33/support/toolchains/sh_4/bin/sh4-streamboard-linux-gnu-
|  CC       = /root/s33/support/toolchains/sh_4/bin/sh4-streamboard-linux-gnu-gcc
| Settings:
|  CONF_DIR = /var/keys
|  CC_OPTS  = -Os -ggdb -pipe -ffunction-sections -fdata-sections
|  CC_WARN  = -W -Wall -Wshadow -Wredundant-decls -Wstrict-prototypes -Wold-style-definition
|  CFLAGS   = -fexpensive-optimizations -DWITH_UTF8=1 -DWITH_UTF8
|  LDFLAGS  = -Wl,--gc-sections -DWITH_UTF8=1 -DWITH_UTF8
|  LIBS     = -lm -lpthread -ldl
|  UseFlags = USE_UTF8=1
| Config:
|  Addons   : WEBIF WEBIF_LIVELOG WEBIF_JQUERY HAVE_DVBAPI READ_SDT_CHARSETS IRDETO_GUESSING WITH_DEBUG MODULE_MONITOR WITH_LB WITH_EMU WITH_SOFTCAM
|  Protocols: CAMD35 CAMD35_TCP NEWCAMD CCCAM CCCSHARE GBOX SCAM
|  Readers  : NAGRA NAGRA_MERLIN IRDETO CONAX CRYPTOWORKS SECA VIACCESS VIDEOGUARD DRE TONGFANG BULCRYPT GRIFFIN DGCRYPT
|  CardRdrs : PHOENIX INTERNAL STINGER
|  Compiler : sh4-streamboard-linux-gnu-gcc (crosstool-NG 1.16.0) 4.6.3
|  Config   : build/sh4-streamboard-linux-gnu/config.mak
|  Binary   : /root/s33/support/binaries/oscam-svn11638-sh_4-webif-dvbapi-emu798
+-------------------------------------------------------------------------------
HOSTCC	webif/pages_gen
GEN	webif/pages.c
GEN	Compressed 408080 template bytes into 166320 bytes. 241760 saved bytes (59.24%).
CC	cscrypt/bn_ctx.c
CC	cscrypt/bn_add.c
CC	cscrypt/bn_asm.c
CC	cscrypt/aes.c
CC	cscrypt/bn_div.c
CC	cscrypt/bn_exp.c
CC	cscrypt/bn_mul.c
CC	cscrypt/bn_lib.c
CC	cscrypt/bn_print.c
CC	cscrypt/bn_shift.c
CC	cscrypt/bn_sqr.c
CC	cscrypt/bn_word.c
CC	cscrypt/mem.c
CC	cscrypt/i_cbc.c
CC	cscrypt/i_ecb.c
CC	cscrypt/i_skey.c
CC	cscrypt/rc6.c
CC	cscrypt/sha1.c
CC	cscrypt/md5.c
CC	cscrypt/des.c
CC	cscrypt/fast_aes.c
CC	cscrypt/sha256.c
CC	cscrypt/mdc2.c
CC	csctapi/atr.c
CC	csctapi/icc_async.c
CC	csctapi/io_serial.c
CC	csctapi/protocol_t0.c
CC	csctapi/protocol_t1.c
CC	csctapi/ifd_phoenix.c
CC	csctapi/ifd_sci.c
CC	minilzo/minilzo.c
CC	csctapi/ifd_stinger.c
CC	module-camd35.c
CC	module-cccam.c
CC	module-cccshare.c
CC	module-emulator.c
CC	module-emulator-osemu.c
CC	module-emulator-streamserver.c
CC	module-emulator-cryptoworks.c
CC	module-emulator-biss.c
CC	module-emulator-director.c
CC	module-emulator-irdeto.c
CC	module-emulator-nagravision.c
CC	module-emulator-powervu.c
CC	module-emulator-viaccess.c
CC	ffdecsa/ffdecsa.c
CC	module-dvbapi-chancache.c
CC	module-dvbapi.c
CC	module-gbox-helper.c
CC	module-gbox-sms.c
CC	module-gbox-remm.c
CC	module-gbox-cards.c
CC	module-gbox.c
CC	module-ird-guess.c
CC	module-monitor.c
CC	module-newcamd.c
CC	module-newcamd-des.c
CC	module-scam.c
CC	module-stat.c
CC	module-webif-lib.c
CC	module-webif-tpl.c
CC	module-webif.c
CC	webif/pages.c
CC	reader-common.c
CC	reader-bulcrypt.c
CC	reader-conax.c
CC	reader-cryptoworks.c
CC	reader-dgcrypt.c
CC	reader-dre.c
CC	reader-dre-cas.c
CC	reader-dre-common.c
CC	reader-dre-st20.c
CC	reader-griffin.c
CC	reader-irdeto.c
CC	reader-nagra-common.c
CC	reader-nagra.c
CC	reader-nagracak7.c
CC	reader-seca.c
CC	reader-tongfang.c
CC	reader-viaccess.c
CC	reader-videoguard-common.c
CC	reader-videoguard1.c
CC	reader-videoguard12.c
CC	reader-videoguard2.c
CC	oscam-aes.c
CC	oscam-array.c
CC	oscam-hashtable.c
CC	oscam-cache.c
CC	oscam-chk.c
CC	oscam-client.c
CC	oscam-conf.c
CC	oscam-conf-chk.c
CC	oscam-conf-mk.c
CC	oscam-config-account.c
CC	oscam-config-global.c
CC	oscam-config-reader.c
CC	oscam-config.c
CC	oscam-ecm.c
CC	oscam-emm.c
CC	oscam-emm-cache.c
CC	oscam-failban.c
CC	oscam-files.c
CC	oscam-garbage.c
CC	oscam-lock.c
CC	oscam-log.c
CC	oscam-log-reader.c
CC	oscam-llist.c
CC	oscam-net.c
CC	oscam-reader.c
CC	oscam-simples.c
CC	oscam-string.c
CC	oscam-time.c
CC	oscam-work.c
CC	oscam.c
CONF	build/sh4-streamboard-linux-gnu/config.c
LINK	/root/s33/support/binaries/oscam-svn11638-sh_4-webif-dvbapi-emu798.debug
build/sh4-streamboard-linux-gnu/module-emulator-biss.o: In function `parse_session_data_descriptor':
/root/s33/oscam-svn/module-emulator-biss.c:649: undefined reference to `RSA_private_decrypt'
build/sh4-streamboard-linux-gnu/module-emulator-biss.o: In function `biss_read_pem':
/root/s33/oscam-svn/module-emulator-biss.c:887: undefined reference to `PEM_read_RSAPrivateKey'
/root/s33/oscam-svn/module-emulator-biss.c:887: undefined reference to `i2d_RSA_PUBKEY'
/root/s33/oscam-svn/module-emulator-biss.c:887: undefined reference to `EVP_MD_CTX_create'
/root/s33/oscam-svn/module-emulator-biss.c:887: undefined reference to `EVP_sha256'
/root/s33/oscam-svn/module-emulator-biss.c:887: undefined reference to `EVP_DigestInit_ex'
/root/s33/oscam-svn/module-emulator-biss.c:887: undefined reference to `EVP_DigestUpdate'
/root/s33/oscam-svn/module-emulator-biss.c:887: undefined reference to `EVP_DigestFinal_ex'
/root/s33/oscam-svn/module-emulator-biss.c:887: undefined reference to `EVP_MD_CTX_destroy'
collect2: ld returned 1 exit status
make[1]: *** [Makefile:436: /root/s33/support/binaries/oscam-svn11638-sh_4-webif-dvbapi-emu798.debug] Error 1
make: *** [Makefile:408: all] Error 2
`

**Comment by gorgone** [comment]
make a ticket in the oscam trac
