### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by tedy58** [gorgone/s3_releases#6]
[bg.tar.gz](https://github.com/gorgone/s3_releases/files/3525994/bg.tar.gz)
Here is translation in Bulgarian
Tested in Ubuntu and Mint

**Comment by numind06** [comment]
[es.gz](https://github.com/gorgone/s3_releases/files/4040262/es.gz)
Spanish translation if required.
Tested in Ubuntu 18

**Comment by gorgone** [comment]
sorry for being late
