### ISSUE TITLE
Request: Add LG webOS TV toolchain

### ISSUE THREAD

**Issue by vpont** [gorgone/s3_releases#64]
Hi,

Would it be possible to add this toolchain: https://github.com/webosbrew/meta-lg-webos-ndk

Releases:
https://github.com/webosbrew/meta-lg-webos-ndk/releases

Thank you in advance.

**Comment by WXbet** [comment]
is this request still up to date?

**Comment by vpont** [comment]
Not useful to me anymore, but it could be for someone else if it's not too much effort. Thanks anyway.

**Comment by WXbet** [comment]
OK, thanks for your reply. I'll close this topic for now.
