### ISSUE TITLE
error compile with EMU

### ISSUE THREAD

**Issue by mikiline-ONE** [gorgone/s3_releases#71]
not possible to compile new Trunk with EMU!
Version         2023.12.320

 patching file -----> config.sh
  Hunk #1 FAILED at 1.

Patch Result
  ------------
  Hunk Count : 13
  Fail Count : 1

--> undefined reference

EMU URL correct? --> https://github.com/oscam-emu/oscam-emu.git

**Comment by WXbet** [comment]
Not an s3 issue, oscam-emu needs to be updated.
