### ISSUE TITLE
error in build Oscam 

### ISSUE THREAD

**Issue by OpenVu** [gorgone/s3_releases#73]
i build with gcc 9

Cam ver: 1.20_svn rev: 11740-799 target: arm-Linuxsat_25-linux-gnueabihf
| Tools:
|  CROSS    = /home/linuxsat/s3_releases/support/toolchains/arm_dreamos-linuxsat_25/bin/arm-Linuxsat_25-linux-gnueabihf-
|  CC       = /home/linuxsat/s3_releases/support/toolchains/arm_dreamos-linuxsat_25/bin/arm-Linuxsat_25-linux-gnueabihf-gcc
| Settings:
|  CONF_DIR = /etc/tuxbox/config
|  CC_OPTS  = -O2 -ggdb -pipe -ffunction-sections -fdata-sections -fomit-frame-pointer -fno-schedule-insns
|  CC_WARN  = -W -Wall -Wshadow -Wredundant-decls -Wstrict-prototypes -Wold-style-definition
|  CFLAGS   = -DWITH_LIBCRYPTO=1 -DWITH_UTF8=1 -DWITH_UTF8
|  LDFLAGS  = -Wl,--gc-sections -DWITH_LIBCRYPTO=1 -DWITH_UTF8=1 -DWITH_UTF8
|  LIBS     = -lcrypto -lm -lpthread -ldl -lrt
|  UseFlags = USE_LIBCRYPTO=1 USE_UTF8=1
| Config:
|  Addons   : WEBIF WEBIF_LIVELOG WEBIF_JQUERY TOUCH HAVE_DVBAPI WITH_EXTENDED_CW READ_SDT_CHARSETS CS_ANTICASC WITH_DEBUG MODULE_MONITOR WITH_LB CS_CACHEEX CS_CACHEEX_AIO CW_CYCLE_CHECK CLOCKFIX
|  Protocols: CAMD35 CAMD35_TCP NEWCAMD CCCAM CCCSHARE GBOX RADEGAST CONSTCW
|  Readers  : NAGRA NAGRA_MERLIN IRDETO CONAX CRYPTOWORKS SECA VIACCESS VIDEOGUARD DRE TONGFANG BULCRYPT GRIFFIN DGCRYPT
|  CardRdrs : PHOENIX INTERNAL
|  Compiler : arm-Linuxsat_25-linux-gnueabihf-gcc (crosstool-NG 1.26.0.22_daf19e1 - simplebuild3) 13.2.0
|  Config   : build/arm-Linuxsat_25-linux-gnueabihf/config.mak
|  Binary   : /home/linuxsat/s3_releases/support/binaries/oscam-svn11740-arm_dreamos-linuxsat_25-webif-dvbapi-emu799
+-------------------------------------------------------------------------------
HOSTCC	webif/pages_gen
GEN	webif/pages.c
GEN	Compressed 488064 template bytes into 182877 bytes. 305187 saved bytes (62.53%).
CC	cscrypt/i_ecb.c
CC	cscrypt/i_cbc.c
CC	cscrypt/i_skey.c
CC	cscrypt/rc6.c
CC	cscrypt/fast_aes.c
CC	cscrypt/sha256.c
CC	cscrypt/des.c
CC	cscrypt/md5.c
CC	csctapi/atr.c
CC	csctapi/protocol_t1.c
CC	csctapi/io_serial.c
CC	csctapi/protocol_t0.c
CC	cscrypt/mdc2.c
CC	csctapi/icc_async.c
CC	csctapi/ifd_phoenix.c
CC	minilzo/minilzo.c
CC	module-cacheex.c
CC	csctapi/ifd_sci.c
CC	module-anticasc.c
CC	module-camd35.c
CC	module-constcw.c
CC	module-cccam.c
CC	module-camd35-cacheex.c
CC	module-cccshare.c
CC	module-cccam-cacheex.c
CC	module-csp.c
CC	module-dvbapi-chancache.c
CC	module-dvbapi.c
CC	module-cw-cycle-check.c
CC	module-gbox-helper.c
CC	module-gbox-sms.c
CC	module-gbox-remm.c
CC	module-gbox-cards.c
CC	module-gbox.c
CC	module-newcamd-des.c
CC	module-monitor.c
CC	module-newcamd.c
CC	module-radegast.c
CC	module-stat.c
CC	module-webif-lib.c
CC	module-webif-tpl.c
CC	module-webif.c
CC	reader-common.c
CC	reader-bulcrypt.c
CC	webif/pages.c
CC	reader-conax.c
CC	reader-cryptoworks.c
CC	reader-dgcrypt.c
CC	reader-dre.c
CC	reader-dre-cas.c
CC	reader-dre-common.c
CC	reader-griffin.c
CC	reader-dre-st20.c
CC	reader-irdeto.c
CC	reader-nagra-common.c
CC	reader-nagracak7.c
CC	reader-nagra.c
CC	reader-seca.c
CC	reader-tongfang.c
CC	reader-viaccess.c
CC	reader-videoguard-common.c
CC	oscam-aes.c
CC	reader-videoguard1.c
CC	reader-videoguard12.c
CC	reader-videoguard2.c
CC	oscam-array.c
CC	oscam-hashtable.c
CC	oscam-cache.c
CC	oscam-chk.c
CC	oscam-client.c
CC	oscam-conf.c
CC	oscam-conf-chk.c
CC	oscam-conf-mk.c
CC	oscam-config-account.c
CC	oscam-config-global.c
CC	oscam-ecm.c
CC	oscam-config.c
CC	oscam-config-reader.c
CC	oscam-emm.c
CC	oscam-files.c
CC	oscam-emm-cache.c
CC	oscam-failban.c
CC	oscam-garbage.c
CC	oscam-lock.c
CC	oscam-log-reader.c
CC	oscam-log.c
CC	oscam-net.c
CC	oscam-simples.c
CC	oscam-string.c
CC	oscam-llist.c
CC	oscam-reader.c
CC	oscam-work.c
CC	oscam-time.c
CONF	build/arm-Linuxsat_25-linux-gnueabihf/config.c
CC	oscam.c
LINK	/home/linuxsat/s3_releases/support/binaries/oscam-svn11740-arm_dreamos-linuxsat_25-webif-dvbapi-emu799.debug
/home/linuxsat/s3_releases/support/toolchains/arm_dreamos-linuxsat_25/lib/gcc/arm-Linuxsat_25-linux-gnueabihf/13.2.0/../../../../arm-Linuxsat_25-linux-gnueabihf/bin/ld: build/arm-Linuxsat_25-linux-gnueabihf/oscam.o: in function `main':
/home/linuxsat/s3_releases/oscam-svn/oscam.c:1948: undefined reference to `stop_stream_server'
/home/linuxsat/s3_releases/support/toolchains/arm_dreamos-linuxsat_25/lib/gcc/arm-Linuxsat_25-linux-gnueabihf/13.2.0/../../../../arm-Linuxsat_25-linux-gnueabihf/bin/ld: build/arm-Linuxsat_25-linux-gnueabihf/oscam.o:(.data.cardreaders+0x8): undefined reference to `cardreader_emu'
/home/linuxsat/s3_releases/support/toolchains/arm_dreamos-linuxsat_25/lib/gcc/arm-Linuxsat_25-linux-gnueabihf/13.2.0/../../../../arm-Linuxsat_25-linux-gnueabihf/bin/ld: build/arm-Linuxsat_25-linux-gnueabihf/module-newcamd.o: in function `newcamd_auth_client':
/home/linuxsat/s3_releases/oscam-svn/module-newcamd.c:1124: undefined reference to `get_emu_prids_for_caid'
/home/linuxsat/s3_releases/support/toolchains/arm_dreamos-linuxsat_25/lib/gcc/arm-Linuxsat_25-linux-gnueabihf/13.2.0/../../../../arm-Linuxsat_25-linux-gnueabihf/bin/ld: build/arm-Linuxsat_25-linux-gnueabihf/reader-common.o: in function `reader_get_cardsystem':
/home/linuxsat/s3_releases/oscam-svn/reader-common.c:160: undefined reference to `reader_emu'
/home/linuxsat/s3_releases/support/toolchains/arm_dreamos-linuxsat_25/lib/gcc/arm-Linuxsat_25-linux-gnueabihf/13.2.0/../../../../arm-Linuxsat_25-linux-gnueabihf/bin/ld: build/arm-Linuxsat_25-linux-gnueabihf/oscam-emm.o: in function `emm_reader_match':
/home/linuxsat/s3_releases/oscam-svn/oscam-emm.c:243: undefined reference to `get_emu_prids_for_caid'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:453: /home/linuxsat/s3_releases/support/binaries/oscam-svn11740-arm_dreamos-linuxsat_25-webif-dvbapi-emu799.debug] Error 1
make: *** [Makefile:425: all] Error 2

 |  TIME  >	[  0 min(s) 5 secs ]

**Comment by WXbet** [comment]
This is related to used oscam-sources. Not an s3 issue.
